window.__iasPET=window.__iasPET||{};
window.__iasPET.start=window.__iasPET.start||function(f,v){var g;try{var p=function(a){var d,b,e,l,c={},m=function(a){return a&&a.replace(/[^\w-_.>\/]/g,"")};d=m(function(a){return a&&a.replace(/\//g,"")}(a.adSlotId));b=a.size&&a.size instanceof Array&&a.size.join(".");e=m(a.adUnitPath);l=function(c){var b="display";"undefined"!==typeof a.type&&null!=c&&"video"==m(c)&&(b="video");return b}(a.type);c.id=d;c=h.extend(c,function(a){var c={};h.isArray(a)&&(a.every(h.isArray)?(a=a.map(function(a){return a.join(".")}).join(","),
c.ss="["+a+"]"):c.s=a.join("."));return c}(a.size));c.p=e;c.t=l;return{toString:function(){var a,b=[];for(a in c)b.push(a+":"+c[a]);return"slot="+("{"+b.join(",")+"}")},isValid:function(){return d&&b&&e}}},x=function(){var a={},d=function(c){return setTimeout(function(){a[c]||(g.diagPix(k.LONG_REQUEST,{message:"threshold:2000"}),g.warn("Long PET request that exceeds 2000ms."))},2E3)},b=function(c){var b=h.getQueryParamByName("iasprofileprobability")||10,l,d,e={};h.chance(b)&&setTimeout(function(){d=
(l=a[c])&&l-c;e.responsetime=d;e.probability=b;g.diagPix(k.PROFILE_RESPONSE,{message:h.buildQueryString(e,":")})},2E3)},e=function(a){return a.width+"."+a.height},l=function(){var a=[],b=f.__iasPET.pubId,l=e(r.getWindowSize(f)),d=e(r.getScreenSize(f)),h=f.__iasPET.sessionId;if(!n.isEmpty()&&b)return a.push("anId="+b),a.push(n),a.push("wr="+l),a.push("sr="+d),a.push("sessionId="+h),g.log("ad slots set: "+n),g.log("anid set: "+b),a.join("&");n.isEmpty()&&g.error("Expected valid ad slot configuration.");
b||g.error("Expecting valid IAS publisher id.");g.diagPix(k.MISSING_DATA)};return{send:function(c,m){var e,f,s=!1,k,q=h.getQueryParamByName("iasendpoint")||"//pixel.adsafeprotected.com/services/pub",p=l(),r=h.isFn(c);p&&(e=function(b){s=h.now();g.log("PET response "+b);a[f]=s;t.updateData(b);r&&c(b);clearTimeout(k)},f=h.now(),a[f]=!1,h.sendXHR(q,p,e,m),k=d(f),b(f),n.clear())}}},u=function(){var a,d,b,e,l=function(c){c&&(d=h.isFn(c.dataHandler)?c.dataHandler:d,a=c.timeout||a,n.setAdSlots(c))};return{setup:function(){b=
new x;e=e||f.__iasPET.queue;e.push=function(c){var e;try{if(h.isFn(c))e=c();else if(h.isObj(c))e=c;else throw Error("Items pushed into the queue must be a function or object");}catch(f){g.error("Error processing queued command: "+f.message)}l(e);b.send(d,a)}},executeCommands:function(){var c,m;if((e=e||f.__iasPET.queue)&&e.length){for(c=0;c<e.length;++c){try{h.isFn(e[c])?m=e[c]():h.isObj(e[c])&&(m=e[c])}catch(w){g.error("Error processing queued command: "+w.message)}l(m)}b.send(d,a)}}}}(),n=function(){var a=
[],d=function(b){(new p(b)).isValid()?a.push(new p(b)):g.error("Missing ad slot id, slot size and/or ad unit path.")};return{setAdSlots:function(a){(a=a.adSlots)&&(a instanceof Array?a.forEach(function(a){d(a)}):h.isObj(a)&&d(a))},clear:function(){a=[]},isEmpty:function(){return 0===a.length},toString:function(){return a.join("&")}}}(),t=function(){var a={},d={},b=function(a,c){a&&h.isFn(a.setTargeting)&&h.forIn(c,function(c,b){g.log("setting targeting: {"+c+": "+b+"}");a.setTargeting(c,b)})},e=function(){var a,
c=f.googletag.pubads().getSlots();c?c.forEach(function(c){(a=h.isFn(c.getSlotElementId)&&c.getSlotElementId())&&b(c,d[a])}):g.error("GPT slots have to be defined before setting slot level keyword targeting")};return{updateData:function(b){var c=JSON.parse(b);b=c.brandSafety;var e=c.slots;a.fr=c.fr;c=function(a,c){h.forIn(a,function(a,b){c[a]=b})};c(b,a);c(e,d)},setTargeting:function(){f.googletag?f.googletag.cmd.push(function(){b(f.googletag.pubads(),a);e()}):(g.error("googletag is not available. Cannot set keyword targeting for GPT."),
g.diagPix(k.GPT_NA));h.isEmptyObj(a)&&g.warn("PET page level data (brand safety, fraud) is not available yet.");h.isEmptyObj(d)&&g.warn("PET slot level data (viewability) is not available yet.")}}}(),k={GPT_NA:"gpt",LONG_REQUEST:"longreq",MISSING_DATA:"m",XHR_NA:"na",PROFILE_RESPONSE:"profile",XHR_GENERAL:"x",XHR_ERROR:"xe",XHR_TIMEOUT:"xt"},r={getWindowSize:function(a){return{width:a.innerWidth||-1,height:a.innerHeight||-1}},getScreenSize:function(a){return{width:a.screen&&a.screen.width||-1,height:a.screen&&
a.screen.height||-1}}};f.__iasPET.queue=f.__iasPET.queue||[];f.__iasPET.VERSION="1.10.0";f.__iasPET.setTargetingForGPT=t.setTargeting;var q=function(){var a=function(a){top.postMessage(a,"*")};return f.postMessage?a:function(){}}();g=function(){var a={},d=function(a,c){var b="background-color: ",d=f.console&&"function"===typeof f.console.error,e=h.getQueryParamByName("iasdebug"),e=e&&"TRUE"===e.toUpperCase();"log"===a?b+="lightgreen":"error"===a?b+="pink":"warn"===a&&(b+="lightyellow");d&&e&&(console.log("%cIAS_DEBUG: "+
c,b),q("DEBUG_petErrorsLog: IAS_DEBUG: "+c))},b=d.bind(null,"log"),e=d.bind(null,"warn");return{diagPix:function(b,c){var e,d,g,k;if(!a[b])try{e=f.__iasPET.pubId||"",d=f.__iasPET.sessionId||"",a[b]=!0,g={code:"pet_"+b,anid:e,sessionId:d},c&&(g.err=encodeURIComponent(c.message)),k=h.buildQueryString(g,":"),(new Image).src="//pixel.adsafeprotected.com/jsdiagnostic?"+k,q("DEBUG_petErrorsReport: //pixel.adsafeprotected.com/jsdiagnostic?"+k)}catch(n){}},error:d.bind(null,"error"),log:b,warn:e}}();var h=
{buildQueryString:function(a,d){var b="";a&&(b=Object.keys(a).reduce(function(b,g){b.push([g,a[g]].join(d));return b},[]).join("&"));return b},getQueryParamByName:function(a){var d,b=f.location.search&&f.location.search.toLowerCase();a=b&&b.indexOf(a);-1!==a&&(d=b.indexOf("=",a)+1,a=b.indexOf("&",d),a=-1===a?v:a,d=decodeURIComponent(b.slice(d,a)));return d},sendXHR:function(a,d,b,e){var f,c;try{if(f=new XMLHttpRequest)c=encodeURI(a+"?"+d),f.open("GET",c),q("DEBUG_petDataRequest: "+c),f.onreadystatechange=
function(){var a,c;if(4===f.readyState&&200===f.status)if(a=f.responseText,c=a.code)g.error("XMLHttpRequest failure code: "+a.code+", message: "+a.message);else if(b)try{b.call({},a)}catch(d){g.error("Error firing the XMLHttpRequest callback: "+d.message)}},e&&(f.timeout=e),f.ontimeout=function(){g.error("XMLHttpRequest timeout event is fired.");g.diagPix(k.XHR_TIMEOUT,{message:"timeout:"+e})},f.onerror=function(a){g.error("XMLHttpRequest error event is fired.");g.diagPix(k.XHR_ERROR,a)},f.send()}catch(h){g.error("Error sending XMLHttpRequest: "+
h.message),g.diagPix(k.XHR_GENERAL,h)}},forIn:function(a,d){for(var b in a)a.hasOwnProperty(b)&&d(b,a[b])},getUID:function(){var a=function(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)};return a()+a()+"-"+a()+"-"+a()+"-"+a()+"-"+a()+a()+a()},extend:function(a,d){d&&Object.keys(d).forEach(function(b){a[b]=d[b]});return a},isArray:function(a){return a instanceof Array},isDef:function(a){return"undefined"!==typeof a},isFn:function(a){return"function"===typeof a},isObj:function(a){return"object"===
typeof a},isEmptyObj:function(a){return 0===Object.getOwnPropertyNames(a).length},now:function(){return(new Date).getTime()},chance:function(a){return 100*Math.random()<a}};"undefined"===typeof XMLHttpRequest?g.diagPix(k.XHR_NA):(f.__iasPET.sessionId=h.getUID(),u.setup(),u.executeCommands())}catch(y){g.error(y.message)}};window.__iasPET.start(window);
